### ISSUE TITLE
Make this repository a template repository

### ISSUE THREAD

**Issue by simonsan** [jbertovic/svelte-axum-project#3]
Within the settings of the repository under **General** ![2022-07-28 21_08_32-Window](https://user-images.githubusercontent.com/14062932/181618427-a019c1f9-a5b6-4156-96da-e318b47b3d39.png)

**Comment by jbertovic** [comment]
Great idea.  

Done.

**Comment by simonsan** [comment]
To add: We could also use `cargo-generate` variables and let people know about it:
https://github.com/cargo-generate/cargo-generate

Documentation here: https://cargo-generate.github.io/cargo-generate/index.html
